// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC67NYOwnJqlByY4x3teTg9_vJ8YLJLcnk',
    appId: '1:614570044589:web:776982a9405c71f0a46a24',
    messagingSenderId: '614570044589',
    projectId: 'ghfdhdfhsgsgsgr',
    authDomain: 'ghfdhdfhsgsgsgr.firebaseapp.com',
    storageBucket: 'ghfdhdfhsgsgsgr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJO08-iCEvBFfoM9QsBau8SbeXIjgjNBQ',
    appId: '1:614570044589:android:0c1acbf4aeb34a2da46a24',
    messagingSenderId: '614570044589',
    projectId: 'ghfdhdfhsgsgsgr',
    storageBucket: 'ghfdhdfhsgsgsgr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQD03tyXlswVNtIyvja5oCDwbTaouDPGE',
    appId: '1:614570044589:ios:86150fc23a2f78cba46a24',
    messagingSenderId: '614570044589',
    projectId: 'ghfdhdfhsgsgsgr',
    storageBucket: 'ghfdhdfhsgsgsgr.appspot.com',
    iosClientId: '614570044589-pa78rj6oeio7gc2s833vfrc5arrq4qm0.apps.googleusercontent.com',
    iosBundleId: 'com.hima.diaryx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQD03tyXlswVNtIyvja5oCDwbTaouDPGE',
    appId: '1:614570044589:ios:4cdde267854e40cca46a24',
    messagingSenderId: '614570044589',
    projectId: 'ghfdhdfhsgsgsgr',
    storageBucket: 'ghfdhdfhsgsgsgr.appspot.com',
    iosClientId: '614570044589-mibun913r6ehc422faje4ru20b7o45tl.apps.googleusercontent.com',
    iosBundleId: 'com.hima.diaryx.RunnerTests',
  );
}
